### ISSUE TITLE
ERR_CERT_DATE_INVALID still occurs

### ISSUE THREAD

**Issue by samsam-026** [OpenClassrooms-Student-Center/5493201-js-for-the-web-gulp#2]
Hi. 
This issue (#1) still seems to be open.
![image](https://user-images.githubusercontent.com/24349997/60764619-ba2e6d00-a0aa-11e9-85ec-33d4fda03956.png)
Please let me know when it can be fixed.

**Comment by willehpeh** [comment]
Hi,
This isn't quite the same issue. The service where the server was hosted is no longer active, and I haven't managed to find a permanent solution with Open Classrooms yet. I'm trying my best to get this resolved, and will let you know as soon as it is. Very sorry for the inconvenience.

**Comment by samsam-026** [comment]
> Hi,
> This isn't quite the same issue. The service where the server was hosted is no longer active, and I haven't managed to find a permanent solution with Open Classrooms yet. I'm trying my best to get this resolved, and will let you know as soon as it is. Very sorry for the inconvenience.

Thanks!

**Comment by samsam-026** [comment]
I'm going to close the ticket since the API used has been switched and now works
